# Environment:
COLOURS:
  - green
  # - red
OBJECT_FOLDERS:
  - cubes
  # - signs
PARTS:
  - cube
  # - plus
ROBOT_STATE_COUNT: 2 # x and y
OBJECT_STATE_COUNT: 3 # x, y and rotation arround z
GOAL_STATE_COUNT: 3 # x, y and rotation arround z
MAX_OBJECT_PER_TYPE: 1
TABLE_CORDS:
  x_min: 0.52 # 0.3
  x_max: 0.9
  y_min: -0.29
  y_max: 0.29
  z: -0.1

# Train
MAX_STEPS: 200
TIMESTEPS: 100000
MODEL: "A2C"
NUM_CPU: 12
EVAL_FREQ: 500
EVAL_EPS: 5

# Simulation
RENDER: true
ASSETS_PATH: "/home/philipp/Documents/repos/rp2024/assets"

